name: 'Add issue/PR to Triage Board'
on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
jobs:
  add-to-triage-project-board:
    uses: cypress-io/cypress/.github/workflows/triage_add_to_project.yml@develop
    secrets: inherit
